### ISSUE TITLE
Go through all IPython notebooks and make sure up to date

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/openforcefield#12]
Generally speaking, IPython notebooks have just been migrated without updating. We need to update all of them.

**Comment by bannanc** [comment]
I'm working on the ones in the examples for chemical environments. I can work on the others as well.

**Comment by davidlmobley** [comment]
Yay. :) Otherwise I will get to this eventually, but if you have time that's awesome.

**Comment by bannanc** [comment]
I did the environment example notebooks in PR #7 
I will plan to go through others next week.

**Comment by bannanc** [comment]
I did this in PR #35 I ran them with python3 so they should all be good to go now.
