### ISSUE TITLE
migrate read_typelist from AtomTyper from smarty into this repo

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/openforcefield#20]
The method read_typelist from AtomTyper is used in smarty and smirky to read in `*.smarts` files. I propose we move this function to utils.py in this repo. I don't think we will need the whole AtomTyper class as that only works with SMARTS strings to match single atoms and we have clearly moved away from that. 

@davidlmobley @jchodera 
I can add this in my current pull request if you agree.

**Comment by davidlmobley** [comment]
@bannanc - sounds fine to me.

**Comment by davidlmobley** [comment]
(Renamed to reflect the fact that I like issues to reflect an action which should be taken.)

**Comment by bannanc** [comment]
added in PR #40
