### ISSUE TITLE
Add tip3p.ffxml to data/forcefield/?

### ISSUE THREAD

**Issue by andrrizzi** [open-forcefield-group/openforcefield#24]
Is there a file for this somewhere?

Having a separate file with the parameters for tip3p water would help setting up simulations in water solvents by simply doing
```python
smirnoff_ffxml = get_data_filename('forcefield/smirnoff99Frosst.ffxml')
tip3p_ffxml = get_data_filename('forcefield/tip3p.ffxml')
ff = ForceField(smirnoff_ffxml, tip3p_ffxml)
```
and avoid hardcoding the parameters in a Python script through `ForceField.addParameter()`. I can work on this today if you agree this is the way to go.

**Comment by davidlmobley** [comment]
Ha, LOL. I don't think we've constructed a SMIRNOFF for TIP3P (or water in general) yet, unless @jchodera did. The hold up was that we didn't support constraints, but now we do support constraints so it should be doable.

One issue I had not thought of before is that currently, we treat charge schemes on a "by system" basis (charges are assigned in the same way for every component of the system) so there is no mechanism to flag certain molecules as requiring library charges (for TIP3P, in this case) versus using charges calculated via a charging mechanism (AM1-BCC).  I'll create an issue to note this as it's something we'll have to resolve eventually.

So, then the question is, how do we deal with charges for water in the interim? I suspect this means we actually have to split the system (with ParmEd, perhaps) and set up both pieces of it separately, using one charging scheme for the solute and another for the water, and then re-combine. If you don't already have an example of splitting/re-combining in this way I can get you one.

But, then there's the issue of the parameter file. We don't currently have one, but I or @bannanc (or you if you like) can create one and put it here and get the others to check it.

**Comment by davidlmobley** [comment]
I agree we want a file with TIP3P parameters, though, and that they should not be coded in a python script.

**Comment by davidlmobley** [comment]
@andrrizzi - There's another way to avoid the charging issue without splitting and re-combining at present: You can assign charges to your molecules BEFORE sending them into the `ForceField` class, and then use `chargeMethod=None` when using `createSystem`. This will retain the existing charges (library charges for water, if you've got them applied already, and AM1-BCC charges for you solute if you've applied them already) so there is no need to split and re-combine.

*BUT - I think at this point you have to split and re-combine anyway* because if we put TIP3P in a separate file, you have to use it to parameterize only the water; molecules not assigned parameters would raise exceptions.

**Comment by andrrizzi** [comment]
> I agree we want a file with TIP3P parameters

Great! I got pretty familiar with the SMIRNOFF and SMARTS, so I'd like to give it a try myself.

I'll continue the discussion about the water in a separate file issue on the thread you just created.

**Comment by jchodera** [comment]
> So, then the question is, how do we deal with charges for water in the interim? I suspect this means we actually have to split the system (with ParmEd, perhaps) and set up both pieces of it separately, using one charging scheme for the solute and another for the water, and then re-combine. If you don't already have an example of splitting/re-combining in this way I can get you one.

We currently support library charges by simply providing an `OEMol` for water with appropriate partial charges as part of the list of molecules needed to construct the forcefield.

We could add a way to override this if we want to hard-code charges in SMIRNOFF format. That may be convenient for testing. For example, we could have
```
<NonbondedForce coulomb14scale="0.833333" lj14scale="0.5" sigma_unit="nanometers" epsilon_unit="kilojoules_per_mole">
   <!-- TIP3P water oxygen with charge override -->
   <Atom smirks="[#1]-[#8X2H2:1]-[#1]" sigma="0.31507524065751241" epsilon="0.635968" charge="-0.8476"/>
   <!-- TIP3P water hydrogen with charge override -->
   <Atom smirks="[#1:1]-[#8X2H2]-[#1]" sigma="0.1" epsilon="0" charge="+0.4238"/>
</NonbondedForce>
<Constraints distance_unit="angstroms">
  <!-- constrain water O-H bond to equilibrium bond length (overrides earlier constraint) -->
  <Constraint smirks="[#1:1]-[#8X2H2:2]-[#1]" distance="0.9572"/>
  <!-- constrain water H...H, calculating equilibrium length from H-O-H equilibrium angle and H-O equilibrium bond lengths -->
  <Constraint smirks="[#1:1]-[#8X2H2]-[#1:2]" distance="1.8532"/>
</Constraints>
```

**Comment by jchodera** [comment]
Also, do we want to use TIP3P, or TIP4P-Ew? 

I think we're stuck with TIP3P for now, since we would have to add virtual sites, but we should be sure our [virtual sites specification](https://github.com/open-forcefield-group/smarty/issues/132) actually permits four-site waters like TIP4P-Ew---I'm not sure it does!

**Comment by davidlmobley** [comment]
@jchodera :

> We currently support library charges by simply providing an OEMol for water with appropriate partial charges as part of the list of molecules needed to construct the forcefield.

Yes, except this only works on a "whole system" basis -- either you charge all of your OEMols first, or none of them. You can't say that you want library charges on only some of the components. :( 

>We could add a way to override this if we want to hard-code charges in SMIRNOFF format. That may be convenient for testing. For example, we could have

```XML
<NonbondedForce coulomb14scale="0.833333" lj14scale="0.5" sigma_unit="nanometers" epsilon_unit="kilojoules_per_mole">
   <!-- TIP3P water oxygen with charge override -->
   <Atom smirks="[#1]-[#8X2H2:1]-[#1]" sigma="0.31507524065751241" epsilon="0.635968" charge="-0.8476"/>
   <!-- TIP3P water hydrogen with charge override -->
   <Atom smirks="[#1:1]-[#8X2H2]-[#1]" sigma="0.1" epsilon="0" charge="+0.4238"/>
```
I agree that this looks like the right way to do it!  (CC #25 )

> I think we're stuck with TIP3P for now, since we would have to add virtual sites, but we should be sure our virtual sites specification actually permits four-site waters like TIP4P-Ew---I'm not sure it does!

For this paper, we absolutely want TIP3P. But, just before you posted, I created an issue ( #27 ) regarding waters with higher number of sites, as you're right, we do not currently support them (and will need to check if our virtual site specification would support them).

**Comment by andrrizzi** [comment]
Ok, thanks! I'll give this a try locally and see if/how I can make it work.

**Comment by bannanc** [comment]
@andrrizzi 
Make sure any SMIRKS you write for water will only work for water and not any other molecules, I recommend:
`[#1]-[#8X2H2+0:1]-[#1]`
Note - without the `+0` it could match "weird" trivalent, positive oxygens

**Comment by andrrizzi** [comment]
Thanks for the tip!
