### ISSUE TITLE
Errors when running the example code. 

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/openforcefield#3]
@davidlmobley and @jchodera 

I was able to download this from the conda channel so at least that is working. However, I tried to run the example in the README as a first pass to check that things were working. I'm getting an error when I try to load the force field ffxml file 

I wrote a script based on the example from the README
```
from openeye.oechem import *
from openforcefield.typing.engines.smirnoff import ForceField
from openforcefield.utils import get_data_filename, extractPositionsFromOEMol, generateTopologyFromOEMol

# Create OEMol of propanol
mol = OEMol()
smiles = "CCCO"
OEParseSmiles(mol, smiles)
OEAddExplicitHydrogens(mol)

# Get positions and topology in OpenMM-compatible format
topology = generateTopologyFromOEMol(mol)

# Load a SMIRNOFF small molecule forcefield for alkanes, ethers, and alcohols
forcefield = ForceField('Frosst_AlkEtOH_parmAtFrosst.ffxml')

# Create the OpenMM system, additionally specifying a list of OEMol objects for the unique molecules in the system
system = forcefield.createSystem(topology, [mol])
```

This is the error message I get when it tries to load the forcefield:
```
Error reading file '/[pythonpath]/openforcefield/typing/engines/smirnoff/data/Frosst_AlkEtOH_parmAtFrosst.ffxml': failed to load external entity "/[pythonpath]/openforcefield/typing/engines/smirnoff/data/Frosst_AlkEtOH_parmAtFrosst.ffxml"
```

I assume this is supposed to access [pythonpath]/openforcefield/data/forcefield/Frosst_AlkEtOH_parmAtFrosst.ffxml

If I copy the ffxml file to my local directory then I get an error when trying to create the system, with the following error:
```
Traceback (most recent call last):
  File "test_openforcefield.py", line 18, in <module>
    system = forcefield.createSystem(topology, [mol])
  File "/Users/cbanana/anaconda/lib/python2.7/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py", line 969, in createSystem
    topology = _Topology(topology, molecules)
  File "/Users/cbanana/anaconda/lib/python2.7/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py", line 197, in __init__
    self._identifyMolecules()
  File "/Users/cbanana/anaconda/lib/python2.7/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py", line 375, in _identifyMolecules
    raise Exception(msg)
Exception: No provided molecule matches topology molecule:
Atom        0           0
```

**Comment by jchodera** [comment]
Thanks for trying this! I hadn't intended the README example to be runnable via cut and paste, but you raise a good point that it should be. The main issue is probably using one of the utility routines to find the FFXML file. I can fix that, or we can add a PR with your nice example above.

We're you able to get the full example at examples/SMIRNOFF_simulation to run?

**Comment by bannanc** [comment]
I only added a couple of lines to your example, whatever we put in the README I think should be useable (i.e. the generic mol was probably fine). 

I just ran the two compare scripts (compare_molecule_energies.py and compare_set_energies.py) at openforcefield/examples/SMIRNOFF_comparison and got the same error on both:
```
Traceback (most recent call last):
  File "compare_set_energies.py", line 44, in <module>
    results = compare_molecule_energies( prmtop, crd, forcefield, mol)
NameError: name 'compare_molecule_energies' is not defined
```
The compare_molecule_energies method is in forcefield_utils which wasn't being imported in the example script. After updating the imports That example does run. I'm starting a pull request now.

**Comment by bannanc** [comment]
@jchodera and @davidlmobley I was going to put in a pull request, but I was denied access specifically:
`ERROR: Permission to open-forcefield-group/openforcefield.git denied to bannanc.`
Could one of you add me to the repo?

**Comment by bannanc** [comment]
I also ran the example at SMIRNOFF_simulation and it works fine.

**Comment by jchodera** [comment]
> Could one of you add me to the repo?

Sorry about thatn, @bannanc! This new GitHub team/org management thing is confusing, but I think I added you both to the developers team and to the Open Forcefield Group org! Let me know if that doesn't work.

**Comment by jchodera** [comment]
> NameError: name 'compare_molecule_energies' is not defined

I think this was moved to `openforcefield.typing.engines.smirnoff`, though we may want to factor things that are generally useful for forcefield engines out to `openforcefield.typing.engines.utils` at some later time.

**Comment by bannanc** [comment]
The updated example in PR #7 will work as written
