### ISSUE TITLE
Sigma and epsilon parameters scrambled with multiple molecules

### ISSUE THREAD

**Issue by andrrizzi** [open-forcefield-group/openforcefield#30]
I found a bug that was causing sigma and epsilon parameters to be incorrectly modified when assigning charges with multiple molecules. [This line](https://github.com/open-forcefield-group/openforcefield/blob/master/openforcefield/typing/engines/smirnoff/forcefield.py#L2023) should use `map_atom_index` instead of `atom_index`.

I'll open a PR to fix this and add a test.

**Comment by davidlmobley** [comment]
Great catch, @andrrizzi ! Was this just for mixtures, or for multiple instances of the same molecule?

**Comment by andrrizzi** [comment]
Just for mixture. Sorry, by multiple molecules I really meant multiple reference molecules.

**Comment by andrrizzi** [comment]
Would you prefer to add this through a branch or a fork? I need push access for the first one. Either way is fine by me anyway.

**Comment by jchodera** [comment]
Let's get you push access by adding you to the team. Otherwise, the Travis tests won't be of any use.

**Comment by davidlmobley** [comment]
Yes, agreed, branch. Did you get added, @andrrizzi ? If not message me on Slack and I can do it right away.

**Comment by jchodera** [comment]
I added him a couple of days ago.
