### ISSUE TITLE
filter molecules utilities directory needs organization

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/openforcefield#37]
I have noticed there are still a lot of intermediate files in the filter molecules directory. It also doesn't have very good documentation on the most recent uses of the scripts contained there. 

I propose removing any intermediate molecule sets that we created when decided what to use to test smarty and smirky, but weren't actually used for anything. Then update the README to reflect what is actually included here and how we used it. 

(as an aside, I'm working on making a "difficult" eMolecules set that only has molecules that are assigned a generic parameter. I could add the script for that here when I'm done if this is the place that makes the most sense for it.)

**Comment by davidlmobley** [comment]
Sounds good to me.

**Comment by bannanc** [comment]
Addressing in PR #40 
See more discussion on [MiniDrugBank issue#2](https://github.com/open-forcefield-group/MiniDrugBank/issues/2)
