### ISSUE TITLE
conda channel needs to be updated

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/openforcefield#38]
We have some undergrads in the group performing gas phase minimizations to compare SMIRNOFF and other forcefields. I instructed our undergrad to download the openforcefield library and stop using her installation of smarty since the most recent version of SMIRNOFF needed the SMIRNOFF name support. 

She followed the directions in the repo with `conda install --yes -c omnia openforcefield` and the version that was downloaded didn't support the name SMIRNOFF in the ffxml file.

**Comment by davidlmobley** [comment]
@bannanc - procedure is to:
a) do a new release (see "releases" tab) 
b) submit a PR to omnia-md/conda-recipes to update the recipe
b') get PR merged
c) Wait for new package to build

I think @nathanmlim can help you with how to do (a) and then I can do the rest.

**Comment by jchodera** [comment]
Yikes! We're way overdue for a new release---there have been 341 commits since the last release:
https://github.com/open-forcefield-group/openforcefield/releases

Let's also try to formulate a strategy for when we should release.

**Comment by andrrizzi** [comment]
I've used the current version of master to setup the SMIRNOFF hydration free energy calculations, so it would be good to have a release tagging the last commit (hash 14a9021).

**Comment by davidlmobley** [comment]
@bannanc - if you won't get to this today (it's quick) LMK and I can do it.

**Comment by bannanc** [comment]
@dmobley I wasn't planning to make time for this today, but I can if you need me to

**Comment by davidlmobley** [comment]
I just made an 0.0.2 point release; will work on updating conda recipe.

**Comment by davidlmobley** [comment]
Resolved and conda recipe updated.
