### ISSUE TITLE
Modify ConstraintGenerator Class' labelForce() Function

### ISSUE THREAD

**Issue by hjuinj** [open-forcefield-group/openforcefield#42]
I think the `labelForce` function of `ConstraintGenerator` class should be modified to be the same as `labelForce` methods in other force generator classes (in /typing/engines/smirnoff/forcefield.py). 

In this class, `unrollSMIRKSMatches` is being called instead of `getSMIRKSMatches_OEMol`.

**Comment by davidlmobley** [comment]
Closed via #49 .
