### ISSUE TITLE
Add explicit icu 58.* as dependency?

### ISSUE THREAD

**Issue by andrrizzi** [open-forcefield-group/openforcefield#44]
I run into a problem today where I had to explicitly tell conda to install `openforcefield` with `icu 58.*` (a dependency for `lxml`) or version `56.1` got installed, which would get me this error:
```
Traceback (most recent call last):
  File "create_input_files.py", line 12, in <module>
    from openforcefield.typing.engines import smirnoff
  File "/cbio/jclab/home/andrrizzi/miniconda/envs/smirnoff/lib/python3.5/site-packages/openforcefield/typing/engines/smirnoff/__init__.py", line 3, in <module>
    from openforcefield.typing.engines.smirnoff.forcefield import *
  File "/cbio/jclab/home/andrrizzi/miniconda/envs/smirnoff/lib/python3.5/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py", line 32, in <module>
    import lxml.etree as etree
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```
The exact commands I used to solve the issue are
```
conda config --add channels omnia --add channels conda-forge
conda create --name smirnoff yank openforcefield packmol 'icu=58.*'
```
(the `icu=58.*` was not there before). This is not a problem when installing only `openforcefield`, but neither `yank` nor `packmol` requires `icu`, so this must be some sort conda weirdness.

I'd modify the conda recipe to explicitly require `58.*` version to avoid this problem.

**Comment by davidlmobley** [comment]
Please do, @andrrizzi !

**Comment by andrrizzi** [comment]
I'd create a new `conda-recipes` release that just bumps the build number, if you agree.

**Comment by davidlmobley** [comment]
Yes, please.
